# Generated by Django 5.1.15 on 2026-08-27 08:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("max_vehicles", models.IntegerField(default=50)),
                ("max_users", models.IntegerField(default=20)),
                ("plan_name", models.CharField(default="PRO", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("FLEET_MANAGER", "Fleet Manager"),
                            ("DISPATCHER", "Dispatcher"),
                            ("ACCOUNTANT", "Accountant"),
                            ("MAINTENANCE_MANAGER", "Maintenance Manager"),
                            ("DRIVER", "Driver / Operator"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="FLEET_MANAGER",
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="drivers/"),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                ("employee_id", models.CharField(blank=True, max_length=50, null=True)),
                ("driving_score", models.IntegerField(default=92)),
                ("is_driver_available", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="fleet.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Geofence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "geofence_type",
                    models.CharField(
                        choices=[
                            ("CIRCLE", "Circular Zone"),
                            ("POLYGON", "Polygon Zone"),
                        ],
                        default="CIRCLE",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WAREHOUSE", "Warehouse / Depot"),
                            ("OFFICE", "Headquarters / Office"),
                            ("SITE", "Construction / Work Site"),
                            ("RESTRICTED", "Restricted Area"),
                            ("PARKING", "Parking Yard"),
                        ],
                        default="SITE",
                        max_length=30,
                    ),
                ),
                ("center_lat", models.FloatField(blank=True, null=True)),
                ("center_lng", models.FloatField(blank=True, null=True)),
                ("radius_meters", models.FloatField(default=500.0)),
                ("coordinates_json", models.TextField(blank=True, default="[]")),
                ("entry_alert", models.BooleanField(default=True)),
                ("exit_alert", models.BooleanField(default=True)),
                ("dwell_alert", models.BooleanField(default=True)),
                ("max_dwell_minutes", models.IntegerField(default=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="fleet.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=150)),
                (
                    "object_repr",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="fleet.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(default="Pro Fleet", max_length=50)),
                (
                    "monthly_price",
                    models.DecimalField(decimal_places=2, default=99.0, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("TRIAL", "Trial"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("current_period_end", models.DateField()),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="fleet.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_code",
                    models.CharField(
                        help_text="Internal ID like TR-101 or JCB-04", max_length=50
                    ),
                ),
                ("registration_number", models.CharField(max_length=50)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("TRUCK", "Truck"),
                            ("VAN", "Delivery Van"),
                            ("CAR", "Car"),
                            ("BUS", "Bus"),
                            ("MOTORCYCLE", "Motorcycle"),
                            ("JCB", "JCB Backhoe Loader"),
                            ("EXCAVATOR", "Excavator"),
                            ("TRACTOR", "Tractor"),
                            ("LOADER", "Wheel Loader"),
                            ("GENERATOR", "Diesel Generator"),
                            ("OTHER", "Other Heavy Equipment"),
                        ],
                        default="TRUCK",
                        max_length=30,
                    ),
                ),
                ("brand", models.CharField(blank=True, default="", max_length=100)),
                ("model", models.CharField(blank=True, default="", max_length=100)),
                ("year", models.IntegerField(default=2023)),
                ("vin", models.CharField(blank=True, default="", max_length=100)),
                (
                    "engine_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("ELECTRIC", "Electric"),
                            ("HYBRID", "Hybrid"),
                            ("CNG", "CNG"),
                        ],
                        default="DIESEL",
                        max_length=20,
                    ),
                ),
                (
                    "mileage_km",
                    models.FloatField(default=0.0, help_text="Total Odometer (km)"),
                ),
                (
                    "engine_hours",
                    models.FloatField(
                        default=0.0, help_text="Total Engine Running Hours"
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MOVING", "Moving"),
                            ("IDLE", "Idle"),
                            ("STOPPED", "Stopped"),
                            ("OFFLINE", "Offline"),
                            ("MAINTENANCE", "Under Maintenance"),
                        ],
                        default="STOPPED",
                        max_length=20,
                    ),
                ),
                ("last_lat", models.FloatField(blank=True, null=True)),
                ("last_lng", models.FloatField(blank=True, null=True)),
                ("last_speed", models.FloatField(default=0.0)),
                ("last_heading", models.FloatField(default=0.0)),
                ("last_gps_update", models.DateTimeField(blank=True, null=True)),
                ("battery_level", models.IntegerField(default=95)),
                ("signal_strength", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "current_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="fleet.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_id", models.CharField(max_length=50, unique=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "start_location",
                    models.CharField(default="Origin Hub", max_length=255),
                ),
                (
                    "destination",
                    models.CharField(default="Destination Site", max_length=255),
                ),
                ("start_lat", models.FloatField(blank=True, null=True)),
                ("start_lng", models.FloatField(blank=True, null=True)),
                ("dest_lat", models.FloatField(blank=True, null=True)),
                ("dest_lng", models.FloatField(blank=True, null=True)),
                ("distance_km", models.FloatField(default=0.0)),
                ("duration_minutes", models.IntegerField(default=0)),
                ("idle_minutes", models.IntegerField(default=0)),
                ("avg_speed_kmh", models.FloatField(default=0.0)),
                ("max_speed_kmh", models.FloatField(default=0.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ASSIGNED", "Assigned"),
                            ("STARTED", "Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trips",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("ENGINE_SERVICE", "Engine Service"),
                            ("OIL_CHANGE", "Oil & Filter Change"),
                            ("BRAKE_SERVICE", "Brake Service"),
                            ("TYRE_REPLACEMENT", "Tyre Replacement"),
                            ("BATTERY", "Battery Check/Replacement"),
                            ("ENGINE_REPAIR", "Engine Repair"),
                            ("INSPECTION", "General Inspection"),
                            ("OTHER", "Other Maintenance"),
                        ],
                        default="ENGINE_SERVICE",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("odometer_at_service", models.FloatField(default=0.0)),
                ("engine_hours_at_service", models.FloatField(default=0.0)),
                (
                    "parts_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "labor_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "workshop_name",
                    models.CharField(
                        blank=True, default="In-House Garage", max_length=150
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("service_date", models.DateField(default=django.utils.timezone.now)),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("next_due_km", models.FloatField(blank=True, null=True)),
                ("next_due_engine_hours", models.FloatField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InspectionChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspect_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tyres_passed", models.BooleanField(default=True)),
                ("brakes_passed", models.BooleanField(default=True)),
                ("lights_passed", models.BooleanField(default=True)),
                ("engine_passed", models.BooleanField(default=True)),
                ("battery_passed", models.BooleanField(default=True)),
                ("fuel_passed", models.BooleanField(default=True)),
                ("mirrors_passed", models.BooleanField(default=True)),
                ("body_passed", models.BooleanField(default=True)),
                ("safety_passed", models.BooleanField(default=True)),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("PASS", "Passed Inspection"),
                            ("FAIL", "Failed - Maintenance Needed"),
                        ],
                        default="PASS",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="inspections/"),
                ),
                (
                    "signature_data",
                    models.TextField(
                        blank=True, default="", help_text="Base64 Canvas signature"
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("speed", models.FloatField(default=0.0)),
                ("heading", models.FloatField(default=0.0)),
                ("accuracy", models.FloatField(default=5.0)),
                ("battery_level", models.IntegerField(default=90)),
                ("is_offline_synced", models.BooleanField(default=False)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gps_logs",
                        to="fleet.trip",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_logs",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="GeofenceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENTER", "Geofence Entry"),
                            ("EXIT", "Geofence Exit"),
                            ("DWELL", "Excessive Dwell Time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("dwell_duration_minutes", models.IntegerField(default=0)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "geofence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="fleet.geofence",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_logs",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_logs",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="geofence",
            name="assigned_vehicles",
            field=models.ManyToManyField(
                blank=True, related_name="geofences", to="fleet.vehicle"
            ),
        ),
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("fuel_quantity_liters", models.FloatField()),
                (
                    "price_per_liter",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("odometer_km", models.FloatField(default=0.0)),
                ("engine_hours", models.FloatField(default=0.0)),
                (
                    "fuel_station",
                    models.CharField(
                        blank=True, default="Shell Station", max_length=150
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(default="Fuel Card", max_length=50),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "suspicious_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fuel_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel"),
                            ("MAINTENANCE", "Maintenance"),
                            ("REPAIRS", "Repairs"),
                            ("TYRES", "Tyres"),
                            ("INSURANCE", "Insurance"),
                            ("TAX", "Tax / License"),
                            ("TOLL", "Toll Fees"),
                            ("PARKING", "Parking"),
                            ("DRIVER_EXPENSE", "Driver Allowance"),
                            ("PARTS", "Parts & Supplies"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                (
                    "receipt_doc",
                    models.FileField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Vehicle Registration"),
                            ("INSURANCE", "Insurance Policy"),
                            ("POLLUTION", "Pollution Control (PUC)"),
                            ("FITNESS", "Fitness Certificate"),
                            ("PERMIT", "Route / Road Permit"),
                            ("LICENSE", "Driver License"),
                            ("OTHER", "Other Legal Document"),
                        ],
                        default="REGISTRATION",
                        max_length=30,
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="documents/"),
                ),
                ("expiry_date", models.DateField()),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DispatchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_code", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("destination_address", models.CharField(max_length=255)),
                ("dest_lat", models.FloatField(blank=True, null=True)),
                ("dest_lng", models.FloatField(blank=True, null=True)),
                ("scheduled_time", models.DateTimeField()),
                ("instructions", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ASSIGNED", "Assigned"),
                            ("ACCEPTED", "Accepted"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Completed / Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                (
                    "proof_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="dispatch_proofs/"
                    ),
                ),
                ("customer_signature", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_jobs",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("VEHICLE_OFFLINE", "Vehicle Offline"),
                            ("GEOFENCE_BREACH", "Geofence Breach"),
                            ("EXCESSIVE_IDLE", "Excessive Idle Time"),
                            ("MAINTENANCE_DUE", "Maintenance Due"),
                            ("DOCUMENT_EXPIRY", "Document Expiry"),
                            ("OVERSPEED", "Overspeed Alert"),
                            ("SUSPICIOUS_FUEL", "Suspicious Fuel Entry"),
                            ("INSPECTION_FAIL", "Inspection Failure"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("WARNING", "Warning"),
                            ("DANGER", "Critical Danger"),
                        ],
                        default="WARNING",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="fleet.organization",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
