# Generated by Django 5.1.15 on 2026-08-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="country_code",
            field=models.CharField(default="US", max_length=10),
        ),
        migrations.AddField(
            model_name="organization",
            name="country_name",
            field=models.CharField(default="United States", max_length=50),
        ),
        migrations.AddField(
            model_name="organization",
            name="currency_code",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="organization",
            name="currency_symbol",
            field=models.CharField(default="$", max_length=10),
        ),
    ]
