# Generated by Django 5.1.15 on 2026-08-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active Status"),
        ),
    ]
