# Generated by Django 5.1.15 on 2026-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency_symbol",
            field=models.CharField(default="$", max_length=5),
        ),
    ]
