# Generated by Django 5.1.15 on 2026-08-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("properties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("rent_due_day", models.IntegerField(default=1)),
                ("grace_period_days", models.IntegerField(default=5)),
                (
                    "late_fee_amount",
                    models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
                ),
                (
                    "rent_escalation_pct",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("notice_period_days", models.IntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("EXPIRING_SOON", "Expiring Soon"),
                            ("EXPIRED", "Expired"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="ACTIVE",
                        max_length=30,
                    ),
                ),
                (
                    "lease_document",
                    models.FileField(blank=True, null=True, upload_to="lease_docs/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="core.organization",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="properties.property",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        limit_choices_to={"role": "TENANT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leases",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-end_date"],
            },
        ),
    ]
