# Generated by Django 5.1.15 on 2026-08-26 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(default="United States", max_length=100)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
                ("currency_symbol", models.CharField(default="$", max_length=10)),
                (
                    "currency_position",
                    models.CharField(
                        choices=[
                            ("prefix", "Prefix ($100)"),
                            ("suffix", "Suffix (100€)"),
                        ],
                        default="prefix",
                        max_length=10,
                    ),
                ),
                ("decimal_places", models.IntegerField(default=2)),
                (
                    "date_format",
                    models.CharField(
                        choices=[
                            ("MM/DD/YYYY", "MM/DD/YYYY (US, CA)"),
                            ("DD/MM/YYYY", "DD/MM/YYYY (UK, AU, NZ)"),
                            ("DD.MM.YYYY", "DD.MM.YYYY (DE, EU)"),
                            ("YYYY-MM-DD", "YYYY-MM-DD (ISO standard)"),
                        ],
                        default="MM/DD/YYYY",
                        max_length=20,
                    ),
                ),
                (
                    "number_format",
                    models.CharField(
                        choices=[
                            ("1,234.56", "1,234.56 (Standard)"),
                            ("1.234,56", "1.234,56 (European)"),
                            ("1 234,56", "1 234,56 (Space separator)"),
                        ],
                        default="1,234.56",
                        max_length=20,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=20)),
                ("tax_name", models.CharField(default="Sales Tax", max_length=50)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=8.5, max_digits=5),
                ),
                ("tax_id_label", models.CharField(default="Tax ID", max_length=50)),
                (
                    "tax_id_value",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("invoice_prefix", models.CharField(default="INV-", max_length=20)),
                ("po_prefix", models.CharField(default="PO-", max_length=20)),
                ("quote_prefix", models.CharField(default="QT-", max_length=20)),
                ("order_prefix", models.CharField(default="SO-", max_length=20)),
                ("bill_prefix", models.CharField(default="BILL-", max_length=20)),
                ("address", models.TextField(blank=True, default="")),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="org_logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Administrator"),
                            ("SALES_MANAGER", "Sales Manager"),
                            ("PURCHASING_MANAGER", "Purchasing Manager"),
                            ("WAREHOUSE_MANAGER", "Warehouse Manager"),
                            ("SALES_USER", "Sales User"),
                            ("WAREHOUSE_USER", "Warehouse User"),
                            ("ACCOUNTANT", "Accountant"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="OWNER",
                        max_length=30,
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
