# Generated by Django 5.1.15 on 2026-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("Overdue", "Overdue Payment"),
                    ("Udhaar Due Today", "Udhaar Due Today"),
                    ("Payment Received", "Payment Received"),
                    ("Promise", "Payment Promised"),
                    ("Dispute", "Disputed Balance"),
                    ("Low Stock", "Low Inventory Stock"),
                ],
                default="Overdue",
                max_length=50,
            ),
        ),
    ]
