# Generated by Django 5.1.15 on 2026-07-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("audio_transcription", "Audio Transcription"),
                            ("text_annotation", "Text Annotation"),
                            ("trilingual_dataset", "Trilingual Dataset"),
                            ("image_annotation", "Image Annotation"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        help_text="e.g. 500 hours, 10K sentences", max_length=100
                    ),
                ),
                (
                    "timeline",
                    models.CharField(help_text="e.g. 4 weeks, ASAP", max_length=100),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Quote Request",
                "verbose_name_plural": "Quote Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
