# Generated by Django 5.1.15 on 2026-08-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "fuel_liters",
                    models.FloatField(help_text="Volume of fuel filled in Liters"),
                ),
                (
                    "cost_per_liter",
                    models.DecimalField(decimal_places=2, default=94.5, max_digits=10),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "meter_reading",
                    models.FloatField(help_text="Meter reading at fill-up time"),
                ),
                (
                    "hours_run_since_last",
                    models.FloatField(
                        default=0.0,
                        help_text="Operating units run since previous refueling",
                    ),
                ),
                (
                    "efficiency_rate",
                    models.FloatField(
                        default=0.0, help_text="Liters per HR or Liters per 100 KM"
                    ),
                ),
                (
                    "fuel_vendor",
                    models.CharField(
                        blank=True,
                        help_text="Station or site tanker",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "is_abnormal_flag",
                    models.BooleanField(
                        default=False,
                        help_text="True if efficiency is suspicious/abnormal",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_logs",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
