# Generated by Django 5.1.15 on 2026-08-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("APARTMENT", "Apartment Building"),
                            ("HOUSE", "Single Family House"),
                            ("VILLA", "Villa / Townhouse"),
                            ("OFFICE", "Office Complex"),
                            ("SHOP", "Retail Shop"),
                            ("WAREHOUSE", "Warehouse"),
                            ("COMMERCIAL", "Commercial Building"),
                            ("MIXED_USE", "Mixed-Use Property"),
                        ],
                        default="APARTMENT",
                        max_length=30,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("zip_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="United States", max_length=100)),
                (
                    "purchase_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "current_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="property_photos/"
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "PROPERTY_MANAGER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to="core.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "PROPERTY_OWNER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Properties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="properties.property",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=50)),
                ("floor", models.IntegerField(default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STUDIO", "Studio Apartment"),
                            ("1BHK", "1 Bedroom / 1 Bath"),
                            ("2BHK", "2 Bedroom / 2 Bath"),
                            ("3BHK", "3 Bedroom / 3 Bath"),
                            ("COMMERCIAL", "Commercial Suite"),
                        ],
                        default="2BHK",
                        max_length=30,
                    ),
                ),
                ("area_sqft", models.IntegerField(default=850)),
                ("bedrooms", models.IntegerField(default=2)),
                (
                    "bathrooms",
                    models.DecimalField(decimal_places=1, default=2.0, max_digits=3),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2, default=1500.0, max_digits=10
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2, default=1500.0, max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VACANT", "Vacant"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        default="VACANT",
                        max_length=30,
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="units",
                        to="properties.building",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["unit_number"],
            },
        ),
    ]
