# Generated by Django 5.1.15 on 2026-08-27 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_tier",
                    models.CharField(
                        choices=[
                            ("starter", "Starter Plan (Up to 5 Machines)"),
                            ("pro", "Pro Fleet Plan (Up to 25 Machines)"),
                            ("enterprise", "Enterprise Unlimited Plan"),
                        ],
                        default="pro",
                        max_length=20,
                    ),
                ),
                ("machine_limit", models.IntegerField(default=25)),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2, default=4999.0, max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.organization",
                    ),
                ),
            ],
        ),
    ]
