# Generated by Django 5.1.15 on 2026-08-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("operators", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("rc", "Registration Certificate (RC)"),
                            ("insurance", "Commercial Insurance Policy"),
                            ("fitness", "Fitness Certificate"),
                            ("permit", "Road / Goods Permit"),
                            ("puc", "Pollution Control (PUC)"),
                            ("license", "Operator Heavy License"),
                            ("other", "Other Compliance Document"),
                        ],
                        default="insurance",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("doc_number", models.CharField(max_length=100)),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="machines.machine",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="operators.operator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["expiry_date"],
            },
        ),
    ]
