# Generated by Django 5.1.15 on 2026-08-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("customers", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Udhaar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Due", "Due"),
                            ("Overdue", "Overdue"),
                            ("Payment Promised", "Payment Promised"),
                            ("Partially Paid", "Partially Paid"),
                            ("Paid", "Paid"),
                            ("Disputed", "Disputed"),
                        ],
                        default="Due",
                        max_length=30,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("Verified", "Verified"),
                            ("Payment Claimed", "Payment Claimed"),
                            ("Pending Verification", "Pending Verification"),
                            ("Paid", "Paid"),
                        ],
                        default="Verified",
                        max_length=30,
                    ),
                ),
                ("promised_date", models.DateField(blank=True, null=True)),
                (
                    "promised_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_reminder_sent", models.DateTimeField(blank=True, null=True)),
                ("next_followup_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="udhaars",
                        to="customers.customer",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="udhaars",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-created_at"],
            },
        ),
    ]
