# Generated by Django 5.1.15 on 2026-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udhaar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="udhaar",
            name="late_fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Late Fees Added",
            ),
        ),
        migrations.AddField(
            model_name="udhaar",
            name="promise_broken",
            field=models.BooleanField(
                default=False, verbose_name="Promise Broken Flag"
            ),
        ),
        migrations.AlterField(
            model_name="udhaar",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Original Udhaar Amount"
            ),
        ),
    ]
