# Generated by Django 5.1.15 on 2026-08-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udhaar", "0002_udhaar_late_fee_amount_udhaar_promise_broken_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="udhaar",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AddField(
            model_name="udhaar",
            name="currency_symbol",
            field=models.CharField(default="$", max_length=5),
        ),
    ]
