# Generated by Django 5.1.15 on 2026-08-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive Service (Periodic)"),
                            ("breakdown", "Breakdown Repair"),
                            ("hydraulic", "Hydraulic System Service"),
                            ("engine", "Engine & Transmission Overhaul"),
                            ("tire_track", "Tires / Tracks Service"),
                            ("inspection", "General Inspection / Greasing"),
                        ],
                        default="preventive",
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meter_reading",
                    models.FloatField(
                        help_text="Meter reading when service took place"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "vendor_mechanic",
                    models.CharField(
                        blank=True,
                        help_text="Workshop or mechanic name",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "parts_replaced",
                    models.TextField(
                        blank=True,
                        help_text="e.g. Engine oil filter, hydraulic seal kit",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "next_service_meter",
                    models.FloatField(
                        blank=True,
                        help_text="Target meter reading for next service",
                        null=True,
                    ),
                ),
                ("is_breakdown", models.BooleanField(default=False)),
                (
                    "downtime_hours",
                    models.FloatField(
                        default=0.0, help_text="Equipment downtime in hours"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
