# Generated by Django 5.1.15 on 2026-08-26 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(default="United States", max_length=100)),
                ("currency_code", models.CharField(default="USD", max_length=10)),
                ("currency_symbol", models.CharField(default="$", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("date_format", models.CharField(default="YYYY-MM-DD", max_length=20)),
                ("number_format", models.CharField(default="1,000.00", max_length=20)),
                ("tax_name", models.CharField(default="Sales Tax", max_length=50)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("invoice_prefix", models.CharField(default="INV-", max_length=20)),
                ("quote_prefix", models.CharField(default="QT-", max_length=20)),
                ("order_prefix", models.CharField(default="SO-", max_length=20)),
                ("po_prefix", models.CharField(default="PO-", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("OVERDUE_INVOICE", "Invoice Overdue"),
                            ("LOW_STOCK", "Product Low Stock"),
                            ("EMPLOYEE_ABSENT", "Employee Absent"),
                            ("EXPIRING_DOC", "Document Expiring"),
                            ("PO_RECEIVED", "Purchase Received"),
                            ("PAYMENT_RECEIVED", "Payment Received"),
                            ("SYSTEM", "System Alert"),
                        ],
                        default="SYSTEM",
                        max_length=30,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                ("record_id", models.CharField(blank=True, max_length=100, null=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("MANAGER", "Manager"),
                            ("EMPLOYEE", "Employee"),
                            ("ACCOUNTANT", "Accountant"),
                            ("SALES", "Sales User"),
                            ("WAREHOUSE", "Warehouse User"),
                            ("VIEWER", "Viewer"),
                        ],
                        default="OWNER",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
