# Generated by Django 5.1.15 on 2026-08-27 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fuel", "Fuel Expense"),
                            ("maintenance", "Parts & Service Maintenance"),
                            ("operator_salary", "Operator Wages / Allowance"),
                            ("transport", "Machine Towing & Transport"),
                            ("emi_lease", "Machine Loan EMI / Lease"),
                            ("other", "General Operating Expense"),
                        ],
                        default="maintenance",
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "vendor_recipient",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense_logs",
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_logs",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "hours_billed",
                    models.FloatField(
                        default=0.0, help_text="Hours or days operated for this invoice"
                    ),
                ),
                (
                    "billing_type",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly Rate Billing"),
                            ("daily", "Daily Rental Rate"),
                            ("monthly_contract", "Monthly Dedicated Contract"),
                            ("fixed_job", "Fixed Project Milestone"),
                        ],
                        default="hourly",
                        max_length=30,
                    ),
                ),
                ("client_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid / Settled"),
                            ("billed", "Invoiced / Pending"),
                            ("overdue", "Overdue Payment"),
                        ],
                        default="paid",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_logs",
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_logs",
                        to="tenants.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revenue_logs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
