# Generated by Django 5.1.15 on 2026-08-27 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("reg_number", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("jcb", "JCB Backhoe Loader"),
                            ("excavator", "Excavator"),
                            ("crane", "Crane"),
                            ("dumper", "Dumper / Tipper"),
                            ("loader", "Wheel Loader"),
                            ("tractor", "Tractor"),
                            ("generator", "Diesel Generator"),
                            ("truck", "Heavy Duty Truck"),
                            ("other", "Other Heavy Equipment"),
                        ],
                        default="jcb",
                        max_length=30,
                    ),
                ),
                (
                    "make_model",
                    models.CharField(
                        help_text="e.g. JCB 3DX, CAT 320D, Tata Prima 2830",
                        max_length=100,
                    ),
                ),
                ("model_year", models.IntegerField(default=2022)),
                (
                    "serial_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tracking_type",
                    models.CharField(
                        choices=[
                            ("hours", "Hours Meter (HR)"),
                            ("km", "Kilometers (KM)"),
                        ],
                        default="hours",
                        max_length=10,
                    ),
                ),
                (
                    "current_meter",
                    models.FloatField(
                        default=0.0, help_text="Current HR or KM reading"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working / Active"),
                            ("idle", "Idle / Available"),
                            ("maintenance", "Scheduled Maintenance"),
                            ("breakdown", "Under Breakdown"),
                            ("rented", "On Client Rent"),
                        ],
                        default="working",
                        max_length=20,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2, default=1200.0, max_digits=12
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2, default=9500.0, max_digits=12
                    ),
                ),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=3500000.0,
                        help_text="Current asset valuation",
                        max_digits=14,
                    ),
                ),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="machines",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MeterLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meter_reading",
                    models.FloatField(help_text="Reading recorded on this date"),
                ),
                (
                    "hours_worked",
                    models.FloatField(
                        default=0.0, help_text="Hours or KM operated today"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_logs",
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_logs",
                        to="tenants.organization",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
