# Generated by Django 5.1.15 on 2026-08-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meterlog",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AlterUniqueTogether(
            name="machine",
            unique_together={("organization", "reg_number")},
        ),
        migrations.RemoveField(
            model_name="meterlog",
            name="created_at",
        ),
        migrations.AddField(
            model_name="machine",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="category",
            field=models.CharField(
                choices=[
                    ("jcb", "JCB Backhoe Loader"),
                    ("excavator", "Excavator"),
                    ("crane", "Mobile Crane"),
                    ("dumper", "Dumper / Tipper"),
                    ("loader", "Wheel Loader"),
                    ("tractor", "Tractor"),
                    ("generator", "Diesel Generator"),
                    ("truck", "Heavy Duty Truck"),
                    ("other", "Other Heavy Equipment"),
                ],
                default="jcb",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="current_meter",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="machine",
            name="daily_rate",
            field=models.DecimalField(decimal_places=2, default=9500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="machine",
            name="estimated_value",
            field=models.DecimalField(
                decimal_places=2, default=3500000.0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=1200.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="machine",
            name="make_model",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="machine",
            name="tracking_type",
            field=models.CharField(
                choices=[
                    ("hours", "Engine Hours (HR)"),
                    ("km", "Odometer Kilometers (KM)"),
                ],
                default="hours",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="meterlog",
            name="hours_worked",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="meterlog",
            name="meter_reading",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="GeofenceZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("center_lat", models.FloatField(default=12.9716)),
                ("center_lng", models.FloatField(default=77.5946)),
                ("radius_km", models.FloatField(default=5.0)),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geofences",
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofences",
                        to="tenants.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationPing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("location_name", models.CharField(max_length=255)),
                ("speed_kmh", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_pings",
                        to="machines.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="MachineLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField(default=12.9716)),
                ("longitude", models.FloatField(default=77.5946)),
                (
                    "location_name",
                    models.CharField(
                        default="NH-48 Expressway Site, Bengaluru", max_length=255
                    ),
                ),
                ("speed_kmh", models.FloatField(default=0.0)),
                ("ignition_on", models.BooleanField(default=True)),
                ("last_ping_time", models.DateTimeField(auto_now=True)),
                (
                    "machine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="machines.machine",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="machine",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="purchase_date",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="serial_number",
        ),
    ]
