# Generated by Django 5.1.15 on 2026-08-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0001_initial"),
        ("operators", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="operator",
            name="performance_score",
            field=models.IntegerField(default=92, help_text="Operator rating 0-100"),
        ),
        migrations.CreateModel(
            name="OperatorAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("leave", "On Leave"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("hours_worked", models.FloatField(default=8.0)),
                ("overtime_hours", models.FloatField(default=0.0)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="operators.operator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="OperatorIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=150)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Minor"),
                            ("medium", "Moderate"),
                            ("high", "Severe Damage"),
                        ],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="machines.machine",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="operators.operator",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
