# Generated by Django 5.1.15 on 2026-08-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accepts_marketing",
            field=models.BooleanField(
                default=True, verbose_name="Opted-in for WhatsApp Broadcasts"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                null=True,
                verbose_name="Credit Limit (₹, 0 = No Limit)",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="promises_broken_count",
            field=models.IntegerField(default=0, verbose_name="Broken Promises Count"),
        ),
        migrations.AddField(
            model_name="customer",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to="customers.customer",
                verbose_name="Referred By Customer",
            ),
        ),
    ]
