# Generated by Django 5.1.15 on 2026-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_accepts_marketing_customer_credit_limit_and_more"),
        ("whatsapp", "0002_whatsappmessage_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="customers", to="whatsapp.tag"
            ),
        ),
    ]
