# Generated by Django 5.1.15 on 2026-08-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("sku", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(default="Filters & Fluids", max_length=50),
                ),
                ("stock_quantity", models.IntegerField(default=10)),
                ("min_stock_threshold", models.IntegerField(default=3)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, default=1500.0, max_digits=10
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spare_parts",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("stock_in", "Stock IN"), ("stock_out", "Stock OUT")],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("date", models.DateField(auto_now_add=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_transactions",
                        to="tenants.organization",
                    ),
                ),
                (
                    "spare_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="inventory.sparepart",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
