# Generated by Django 5.1.15 on 2026-08-26 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("has_action_proposal", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_logs",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAISetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("GEMINI", "Google Gemini AI"),
                            ("OPENAI", "OpenAI (GPT-4o / GPT-3.5)"),
                            ("ANTHROPIC", "Anthropic Claude"),
                            ("OLLAMA", "Local Ollama / Custom API"),
                            ("BUILTIN", "StockFlow Built-in Intelligent Copilot"),
                        ],
                        default="BUILTIN",
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(blank=True, default="", max_length=255)),
                (
                    "model_name",
                    models.CharField(default="gemini-1.5-flash", max_length=100),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("max_daily_queries", models.IntegerField(default=100)),
                (
                    "custom_system_prompt",
                    models.TextField(
                        blank=True,
                        default="You are StockFlow AI, an executive inventory and financial copilot for growing SMBs.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_setting",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
    ]
