# Generated by Django 5.1.15 on 2026-09-01 08:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ContactLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("contact", "General Contact"),
                            ("demo", "Demo Request"),
                            ("trial", "Free Trial Request"),
                        ],
                        default="contact",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(blank=True)),
                ("product_or_service", models.CharField(blank=True, max_length=200)),
                ("preferred_date_time", models.CharField(blank=True, max_length=100)),
                ("source_page", models.CharField(default="Website", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("closed", "Closed"),
                            ("spam", "Spam"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("assigned_staff", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("category", models.CharField(default="General", max_length=100)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("global", "Global / All Pages"),
                            ("homepage", "Homepage Only"),
                            ("product", "Product Pages"),
                            ("service", "Service Pages"),
                            ("contact", "Contact Page"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                ("product_name", models.CharField(blank=True, max_length=200)),
                ("service_name", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FooterConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Milda Data is an enterprise cloud SaaS and regional language AI technology provider empowering modern digital operations."
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        default="© 2026 Milda Data Enterprise. All rights reserved.",
                        max_length=200,
                    ),
                ),
                (
                    "address_display",
                    models.TextField(blank=True, default="Tech Hub, India"),
                ),
                (
                    "contact_email",
                    models.EmailField(default="ab.mishra@yahoo.com", max_length=254),
                ),
                (
                    "phone_display",
                    models.CharField(default="+91 98765 43210", max_length=50),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer Configuration",
                "verbose_name_plural": "Footer Configuration",
            },
        ),
        migrations.CreateModel(
            name="HomePageHero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge",
                    models.CharField(
                        default="NEXT-GEN ENTERPRISE SAAS & AI", max_length=100
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Build & Run Digital Products That Matter",
                        max_length=250,
                    ),
                ),
                (
                    "subheading",
                    models.CharField(
                        default="We design, engineer, and deploy high-performance SaaS products and AI data solutions.",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        default="Automate financial ledgers, heavy machinery fleets, property portfolios, inventory purchasing, and regional language AI model training on a single unified platform."
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/homepage/"),
                ),
                ("hero_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "hero_video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube, Vimeo or MP4 URL",
                        max_length=500,
                    ),
                ),
                (
                    "primary_cta",
                    models.CharField(default="Explore Products", max_length=100),
                ),
                (
                    "primary_cta_url",
                    models.CharField(default="/products/", max_length=300),
                ),
                (
                    "secondary_cta",
                    models.CharField(default="Book Live Demo", max_length=100),
                ),
                (
                    "secondary_cta_url",
                    models.CharField(default="/contact/", max_length=300),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage Hero",
                "verbose_name_plural": "Homepage Hero",
            },
        ),
        migrations.CreateModel(
            name="HomeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(default="10+", max_length=50)),
                ("label", models.CharField(default="SaaS Products", max_length=100)),
                (
                    "icon",
                    models.CharField(
                        default="🚀", help_text="Emoji or Icon class", max_length=50
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeWhyChoose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="⚡", max_length=50)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cms/why/"),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "content",
                    models.TextField(help_text="Rich text / HTML legal policy body"),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_published", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="cms/media/")),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        default="image",
                        max_length=20,
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=250)),
                ("description", models.TextField(blank=True)),
                ("file_size_bytes", models.PositiveIntegerField(default=0)),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, help_text="e.g. 1920x1080", max_length=50
                    ),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-upload_date"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(default="Website Footer", max_length=100)),
                (
                    "unsubscribe_token",
                    models.CharField(blank=True, default=uuid.uuid4, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("client_name", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(default="Enterprise Software", max_length=100),
                ),
                ("short_description", models.TextField()),
                ("challenge", models.TextField(blank=True)),
                ("solution", models.TextField(blank=True)),
                ("results", models.TextField(blank=True)),
                (
                    "features",
                    models.TextField(blank=True, help_text="One feature per line"),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True, help_text="Comma-separated", max_length=300
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/projects/"),
                ),
                ("featured_image_url", models.URLField(blank=True, max_length=500)),
                ("video_url", models.URLField(blank=True, max_length=500)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SEOSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_identifier",
                    models.CharField(
                        choices=[
                            ("homepage", "Homepage"),
                            ("products", "Products Catalog"),
                            ("services", "Services Directory"),
                            ("projects", "Projects Portfolio"),
                            ("blog", "Blog Index"),
                            ("about", "About Us Page"),
                            ("contact", "Contact Us Page"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "site_title",
                    models.CharField(help_text="SEO Title Tag", max_length=200),
                ),
                (
                    "meta_description",
                    models.TextField(help_text="Meta Description Tag"),
                ),
                ("keywords", models.CharField(blank=True, max_length=300)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/seo/"),
                ),
                ("og_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "robots_directive",
                    models.CharField(default="index, follow", max_length=100),
                ),
                ("include_in_sitemap", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO Setting",
                "verbose_name_plural": "SEO Settings",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "short_description",
                    models.TextField(help_text="Shown on service cards"),
                ),
                (
                    "full_description",
                    models.TextField(help_text="HTML / Rich Text full service details"),
                ),
                ("icon", models.CharField(default="🛠️", max_length=50)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/services/"),
                ),
                ("hero_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "features",
                    models.TextField(blank=True, help_text="One feature per line"),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, help_text="One benefit per line"),
                ),
                (
                    "process_steps",
                    models.TextField(
                        blank=True, help_text="Step 1: Description (one per line)"
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated e.g. Python, Django, PyTorch, PostgreSQL",
                        max_length=300,
                    ),
                ),
                (
                    "pricing_info",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Custom Quote / Starting from $499",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(default="Milda Data", max_length=200),
                ),
                (
                    "tagline",
                    models.CharField(
                        default="Enterprise SaaS Applications & Regional Language AI Tools",
                        max_length=300,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="cms/settings/"),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        default="https://i.postimg.cc/43gxKLrL/6e2fd4bb-c219-46d7-a5a3-21d4df5b9461.png",
                        max_length=500,
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="cms/settings/"),
                ),
                ("default_language", models.CharField(default="en", max_length=20)),
                ("default_currency", models.CharField(default="INR", max_length=10)),
                (
                    "contact_email",
                    models.EmailField(default="ab.mishra@yahoo.com", max_length=254),
                ),
                (
                    "support_email",
                    models.EmailField(default="support@mildadata.com", max_length=254),
                ),
                (
                    "phone_number",
                    models.CharField(default="+91 98765 43210", max_length=50),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, default="Milda Data Enterprise HQ, Tech Hub, India"
                    ),
                ),
                (
                    "business_hours",
                    models.CharField(
                        default="Mon - Fri: 9:00 AM - 6:00 PM IST", max_length=200
                    ),
                ),
                (
                    "social_linkedin",
                    models.URLField(blank=True, default="https://linkedin.com"),
                ),
                (
                    "social_twitter",
                    models.URLField(blank=True, default="https://twitter.com"),
                ),
                (
                    "social_github",
                    models.URLField(blank=True, default="https://github.com"),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True, help_text="e.g. G-XXXXXXXXXX", max_length=50
                    ),
                ),
                (
                    "default_cta_title",
                    models.CharField(
                        default="Ready to Automate Your Business?", max_length=200
                    ),
                ),
                (
                    "default_cta_subtitle",
                    models.TextField(
                        default="Deploy our enterprise SaaS tools in under 5 minutes with zero setup friction."
                    ),
                ),
                (
                    "default_cta_button_text",
                    models.CharField(default="Explore SaaS Catalog", max_length=100),
                ),
                (
                    "default_cta_button_url",
                    models.CharField(default="/products/", max_length=300),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("role", models.CharField(max_length=150)),
                ("bio", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="cms/team/"),
                ),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("public_email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("company", models.CharField(blank=True, max_length=150)),
                ("role", models.CharField(blank=True, max_length=150)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="cms/testimonials/"
                    ),
                ),
                ("photo_url", models.URLField(blank=True, max_length=500)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="1 to 5 stars"),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Product or Service associated",
                        max_length=200,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                (
                    "action",
                    models.CharField(
                        help_text="e.g. Product Created, Blog Published, Settings Saved",
                        max_length=100,
                    ),
                ),
                ("target_model", models.CharField(max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("slug", models.SlugField(blank=True, max_length=270, unique=True)),
                (
                    "excerpt",
                    models.TextField(help_text="Short summary for article cards"),
                ),
                (
                    "content",
                    models.TextField(help_text="Full article body (Rich Text / HTML)"),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/blog/"),
                ),
                ("featured_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "author_name",
                    models.CharField(
                        default="Milda Data Editorial Team", max_length=100
                    ),
                ),
                ("reading_time", models.CharField(default="5 min read", max_length=50)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="published",
                        max_length=20,
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                (
                    "preview_token",
                    models.CharField(blank=True, default=uuid.uuid4, max_length=64),
                ),
                ("seo_title", models.CharField(blank=True, max_length=200)),
                ("meta_description", models.TextField(blank=True)),
                ("og_image_url", models.URLField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="website_cms.blogcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NavigationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "url",
                    models.CharField(
                        help_text="e.g. /products/ or https://...", max_length=300
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="website_cms.navigationitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="UserPermissionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin"),
                            ("admin", "Administrator"),
                            ("content_manager", "Content Manager"),
                            ("product_manager", "Product Manager"),
                            ("support", "Support Specialist"),
                            ("marketing", "Marketing Lead"),
                        ],
                        default="admin",
                        max_length=30,
                    ),
                ),
                ("can_publish", models.BooleanField(default=True)),
                ("can_delete", models.BooleanField(default=True)),
                ("can_manage_settings", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_role",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
