# Generated by Django 5.1.15 on 2026-08-25 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_business_is_active"),
        ("udhaar", "0002_udhaar_late_fee_amount_udhaar_promise_broken_and_more"),
        ("whatsapp", "0003_whatsappconversation_conversation_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("invoice_created", "📄 Invoice Created"),
                            ("collection_created", "📋 Collection Added"),
                            ("reminder_sent", "📲 Reminder Sent"),
                            ("promise_made", "🤝 Payment Promised"),
                            ("promise_missed", "⚠️ Promise Missed"),
                            ("partial_payment", "💰 Partial Payment Received"),
                            ("full_payment", "✅ Payment Received (Full)"),
                            ("due_date_changed", "📅 Due Date Changed"),
                            ("status_changed", "🔄 Status Updated"),
                            ("note_added", "📝 Note Added"),
                            ("escalated", "🚨 Escalated"),
                            ("disputed", "❌ Disputed"),
                        ],
                        default="note_added",
                        max_length=50,
                        verbose_name="Activity Type",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Amount (if applicable)",
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        blank=True,
                        help_text="Username or 'System Auto'",
                        max_length=100,
                        verbose_name="Performed By",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
                (
                    "udhaar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="udhaar.udhaar",
                        verbose_name="Collection (Udhaar)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collection Activity",
                "verbose_name_plural": "Collection Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReminderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "days_offset",
                    models.IntegerField(
                        help_text="Negative = before due date, Positive = days overdue",
                        verbose_name="Days Offset",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. '3 days before due', '7 days overdue'",
                        max_length=100,
                        verbose_name="Rule Label",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="Enabled"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminder_rules",
                        to="whatsapp.whatsappmessagetemplate",
                        verbose_name="Message Template",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder Rule",
                "verbose_name_plural": "Reminder Rules",
                "ordering": ["order", "days_offset"],
            },
        ),
    ]
