# Generated by Django 5.1.15 on 2026-08-18 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("customers", "0003_customer_tags"),
        ("products", "0002_product_barcode_alter_product_sku"),
        ("sales", "0001_initial"),
        ("whatsapp", "0003_whatsappconversation_conversation_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "Pending Owner Confirmation",
                                "Pending Owner Confirmation",
                            ),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending Owner Confirmation",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
                (
                    "converted_sale",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_orders",
                        to="sales.sale",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="draft_orders",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SalesAgentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, verbose_name="Enable AI Sales Agent"
                    ),
                ),
                (
                    "auto_draft_orders",
                    models.BooleanField(
                        default=True,
                        verbose_name="Auto-Draft Orders for Owner Approval",
                    ),
                ),
                (
                    "greeting_message",
                    models.TextField(
                        default="Namaste! Main aapka AI Sales Assistant hu. Aap humare products ke baare me pooch sakte hain (Price, Stock, Order).",
                        verbose_name="AI Greeting / Tone Message",
                    ),
                ),
                (
                    "anti_spam_window_hours",
                    models.IntegerField(
                        default=24, verbose_name="Anti-Spam Window (Hours)"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Sales Agent Settings",
            },
        ),
        migrations.CreateModel(
            name="SalesBlastHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_count", models.IntegerField(default=0)),
                ("reply_count", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blast_histories",
                        to="products.product",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blast_histories",
                        to="whatsapp.whatsappmessagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerProductBlastLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_blasted_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_blast_logs",
                        to="customers.customer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_blast_logs",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_blasted_at"],
                "unique_together": {("business", "customer", "product")},
            },
        ),
    ]
