# Generated by Django 5.1.15 on 2026-08-18 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("sales_agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesAgentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Template Name"),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Message"),
                            ("product_inquiry", "Product Inquiry Response"),
                            ("price_reply", "Product Price Reply"),
                            ("stock_reply", "Stock Availability Reply"),
                            ("recommendation", "Product Recommendation"),
                            (
                                "customer_interested",
                                "Customer Interested / Quantity Prompt",
                            ),
                            ("order_confirmation", "Order Confirmation / Draft"),
                            ("payment_message", "Payment Message / Link"),
                            ("order_status", "Order Status Message"),
                            ("followup", "Follow-up Message"),
                            ("out_of_stock", "Out-of-Stock Message"),
                            ("human_handoff", "Human Handoff Message"),
                            ("general", "General AI Reply"),
                        ],
                        max_length=50,
                        verbose_name="Message Type",
                    ),
                ),
                ("content", models.TextField(verbose_name="Message Template Content")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["message_type", "name"],
            },
        ),
    ]
