# Generated by Django 5.1.15 on 2026-08-27 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("machines", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="GST / VAT / Tax ID",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_customers",
                        to="tenants.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Rental Rate"),
                            ("hourly", "Hourly Billed Rate"),
                            ("monthly", "Monthly Contract"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("agreed_rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "handover_meter",
                    models.FloatField(help_text="Meter reading at handover time"),
                ),
                (
                    "return_meter",
                    models.FloatField(
                        blank=True, help_text="Meter reading upon return", null=True
                    ),
                ),
                (
                    "handover_condition",
                    models.TextField(
                        blank=True,
                        default="Passed 15-point inspection cleanly.",
                        null=True,
                    ),
                ),
                ("return_condition", models.TextField(blank=True, null=True)),
                (
                    "damage_charges",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active Rental"),
                            ("completed", "Completed & Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_contracts",
                        to="machines.machine",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_contracts",
                        to="tenants.organization",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="rentals.rentalcustomer",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
