# Generated by Django 5.1.15 on 2026-08-18 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_business_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAdvisorQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(verbose_name="User Question")),
                ("answer", models.TextField(verbose_name="AI Advisor Answer")),
                (
                    "asked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-asked_at"],
            },
        ),
        migrations.CreateModel(
            name="AIBusinessInsightCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date_range_code",
                    models.CharField(
                        default="30_days",
                        max_length=50,
                        verbose_name="Date Range Filter",
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        default="Needs Attention",
                        max_length=50,
                        verbose_name="Business Health Status",
                    ),
                ),
                (
                    "health_summary",
                    models.TextField(
                        blank=True, verbose_name="Business Health Summary Text"
                    ),
                ),
                (
                    "insight_json",
                    models.JSONField(
                        default=dict, verbose_name="Structured AI Insight JSON Payload"
                    ),
                ),
                (
                    "last_analyzed_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Analysis Timestamp"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_analyzed_at"],
                "unique_together": {("business", "date_range_code")},
            },
        ),
    ]
