# Generated by Django 5.1.15 on 2026-08-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_salarypayment"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarypayment",
            name="payout_type",
            field=models.CharField(
                choices=[
                    ("Salary", "Monthly Salary"),
                    ("Daily Wage", "Daily Wage"),
                    ("Weekly Wage", "Weekly Wage"),
                    ("Task / Piece Work", "Task / Piece Work Pay"),
                    ("Advance", "Salary Advance"),
                    ("Commission / Bonus", "Commission / Bonus"),
                ],
                default="Salary",
                max_length=50,
            ),
        ),
    ]
