# Generated by Django 5.1.15 on 2026-08-18 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "upi_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="UPI ID (e.g. 9876543210@upi)",
                    ),
                ),
                (
                    "payee_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Payee / Merchant Name"
                    ),
                ),
                (
                    "payment_link",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Static Payment Link / Razorpay / PhonePe Link",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="UPI QR Code Image",
                    ),
                ),
                (
                    "whatsapp_phone_number_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("whatsapp_api_token", models.CharField(blank=True, max_length=500)),
                (
                    "reminder_before_due_days",
                    models.IntegerField(
                        default=2, verbose_name="Send reminder N days before due date"
                    ),
                ),
                (
                    "reminder_on_due_date",
                    models.BooleanField(
                        default=True, verbose_name="Send reminder on exact due date"
                    ),
                ),
                (
                    "followup_frequency_days",
                    models.IntegerField(
                        default=3,
                        verbose_name="Follow-up frequency after overdue (days)",
                    ),
                ),
                (
                    "auto_send_payment_link",
                    models.BooleanField(
                        default=True,
                        verbose_name="Auto-send UPI link when customer asks 'UPI bhejo'",
                    ),
                ),
                (
                    "stop_reminders_on_payment",
                    models.BooleanField(
                        default=True,
                        verbose_name="Stop automated reminders once payment is recorded",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
