# Generated by Django 5.1.15 on 2026-08-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="enable_late_fees",
            field=models.BooleanField(
                default=False,
                verbose_name="Enable Late Fees / Interest on Overdue Udhaar",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="late_fee_frequency",
            field=models.CharField(
                choices=[
                    ("one_time", "One-Time Charge"),
                    ("recurring", "Recurring (Every 30 Days Overdue)"),
                ],
                default="one_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="late_fee_grace_days",
            field=models.IntegerField(
                default=5, verbose_name="Grace Period (Days past due date)"
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="late_fee_type",
            field=models.CharField(
                choices=[
                    ("flat", "Flat Amount (₹)"),
                    ("percent", "Percentage of Outstanding (%)"),
                ],
                default="flat",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="late_fee_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Late Fee Amount or Percent",
            ),
        ),
    ]
