# Generated by Django 5.1.15 on 2026-08-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0002_businesssettings_enable_late_fees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="ai_api_key",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="AI API Key"
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="ai_api_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Custom API Endpoint URL"
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="ai_model_name",
            field=models.CharField(
                default="gemini-1.5-flash",
                max_length=100,
                verbose_name="AI Model Name (e.g. gemini-1.5-flash, gpt-4o-mini)",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="ai_provider",
            field=models.CharField(
                choices=[
                    ("gemini", "Google Gemini AI"),
                    ("openai", "OpenAI ChatGPT"),
                    ("custom_llm", "Custom OpenAI-Compatible API"),
                    ("rule_based", "Built-in Analytics Engine (No API Key Required)"),
                ],
                default="gemini",
                max_length=50,
                verbose_name="AI Provider",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="ai_temperature",
            field=models.FloatField(default=0.2, verbose_name="AI Temperature"),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="is_ai_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable AI Features"),
        ),
    ]
