# Generated by Django 5.1.15 on 2026-08-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0003_businesssettings_ai_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="currency",
            field=models.CharField(
                choices=[
                    ("INR", "₹ INR (India)"),
                    ("USD", "$ USD (United States / Global)"),
                    ("GBP", "£ GBP (United Kingdom)"),
                    ("EUR", "€ EUR (European Union)"),
                ],
                default="INR",
                max_length=10,
                verbose_name="Business Currency",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="currency_symbol",
            field=models.CharField(
                default="₹", max_length=5, verbose_name="Currency Symbol"
            ),
        ),
    ]
