# Generated by Django 5.1.15 on 2026-08-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings_app", "0004_businesssettings_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssettings",
            name="country",
            field=models.CharField(
                choices=[
                    ("IN", "🇮🇳 India (INR)"),
                    ("US", "🇺🇸 United States (USD)"),
                    ("GB", "🇬🇧 United Kingdom (GBP)"),
                    ("EU", "🇪🇺 European Union (EUR)"),
                    ("CA", "🇨🇦 Canada (CAD)"),
                    ("AU", "🇦🇺 Australia (AUD)"),
                    ("AE", "🇦🇪 United Arab Emirates (AED)"),
                ],
                default="US",
                max_length=10,
                verbose_name="Business Country",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="date_format",
            field=models.CharField(
                default="MM/DD/YYYY", max_length=20, verbose_name="Date Format"
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="number_format",
            field=models.CharField(
                choices=[
                    ("standard", "Standard (149,999)"),
                    ("indian", "Indian (1,49,999)"),
                ],
                default="standard",
                max_length=20,
                verbose_name="Number Formatting",
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="phone_code",
            field=models.CharField(
                default="+1", max_length=10, verbose_name="Phone Country Code"
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="tax_label",
            field=models.CharField(
                default="Sales Tax", max_length=20, verbose_name="Tax Label"
            ),
        ),
        migrations.AddField(
            model_name="businesssettings",
            name="timezone",
            field=models.CharField(
                default="America/New_York", max_length=50, verbose_name="Timezone"
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="currency",
            field=models.CharField(
                default="USD", max_length=10, verbose_name="Currency Code"
            ),
        ),
        migrations.AlterField(
            model_name="businesssettings",
            name="currency_symbol",
            field=models.CharField(
                default="$", max_length=5, verbose_name="Currency Symbol"
            ),
        ),
    ]
