# Generated by Django 5.1.15 on 2026-08-26 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("compliance", "0001_initial"),
        ("core", "0001_initial"),
        ("documents", "0001_initial"),
        ("suppliers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceissue",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compliance_issues",
                to="documents.supplierdocument",
            ),
        ),
        migrations.AddField(
            model_name="complianceissue",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_issues",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="complianceissue",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_compliance_issues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="complianceissue",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="compliance_issues",
                to="suppliers.supplier",
            ),
        ),
    ]
