# Generated by Django 5.1.15 on 2026-08-26 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                ("default_expiry_days", models.IntegerField(default=365)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_types",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "code")},
            },
        ),
        migrations.CreateModel(
            name="OnboardingTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("supplier_category", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_templates",
                        to="core.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentRequirement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="suppliers.documenttype",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requirements",
                        to="suppliers.onboardingtemplate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                (
                    "trading_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "supplier_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("category", models.CharField(default="Manufacturing", max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("INVITED", "Invited"),
                            ("IN_REVIEW", "In Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("website", models.URLField(blank=True, null=True)),
                ("company_email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "invitation_token",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ("invitation_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("onboarding_deadline", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("compliance_score", models.IntegerField(default=100)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_suppliers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="core.organization",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suppliers",
                        to="suppliers.onboardingtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierBankDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bank_name", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("account_number", models.CharField(max_length=100)),
                (
                    "routing_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("swift_bic", models.CharField(blank=True, max_length=50, null=True)),
                ("iban", models.CharField(blank=True, max_length=50, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierTaxInformation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tax_id_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gst_vat_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tax_residency_country",
                    models.CharField(default="India", max_length=100),
                ),
                ("is_exempt", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tax_info",
                        to="suppliers.supplier",
                    ),
                ),
            ],
        ),
    ]
