# Generated by Django 5.1.15 on 2026-08-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierbankdetails",
            name="account_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="supplierbankdetails",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="supplierbankdetails",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
