# Generated by Django 5.1.15 on 2026-08-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappmessage",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="voice_notes/"),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="is_voice_note",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="whatsappmessage",
            name="transcript",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#4f46e5", max_length=20, verbose_name="Badge Color Hex"
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("business", "name")},
            },
        ),
        migrations.CreateModel(
            name="WhatsAppCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("message_text", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="campaigns/"),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all", "All Marketing Opted-in Customers"),
                            ("tag", "Specific Customer Tag / Segment"),
                            ("selected", "Manually Selected Customers"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("sent_count", models.IntegerField(default=0)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="accounts.business",
                        verbose_name="Business Tenant",
                    ),
                ),
                (
                    "target_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="whatsapp.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
