# Generated by Django 5.1.15 on 2026-08-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0002_whatsappmessage_audio_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappconversation",
            name="conversation_type",
            field=models.CharField(
                choices=[
                    ("recovery", "Recovery/Udhaar"),
                    ("sales", "Sales/Product Inquiry"),
                ],
                default="recovery",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="whatsappmessagetemplate",
            name="trigger_type",
            field=models.CharField(
                choices=[
                    ("Due Reminder", "Due Reminder"),
                    ("Overdue Reminder", "Overdue Reminder"),
                    ("Promise Confirmation", "Promise Confirmation"),
                    ("Payment Link", "Payment Link"),
                    ("Payment Received", "Payment Received"),
                    ("Sales Blast", "Sales Blast"),
                ],
                max_length=50,
            ),
        ),
    ]
