# Generated by Django 5.1.15 on 2026-08-27 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="is_demo_org",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("PROPERTY_MANAGER", "Property Manager"),
                    ("PROPERTY_OWNER", "Property Owner"),
                    ("ACCOUNTANT", "Accountant"),
                    ("MAINTENANCE_STAFF", "Maintenance Staff"),
                    ("TENANT", "Tenant"),
                    ("GUEST", "Guest Mode User"),
                ],
                default="PROPERTY_MANAGER",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="GuestSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "guest_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guest_session",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
