# Generated by Django 5.1.15 on 2026-08-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_organization_is_demo_org_alter_user_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="currency_code",
            field=models.CharField(
                choices=[
                    ("USD", "$ - US Dollar"),
                    ("EUR", "€ - Euro"),
                    ("GBP", "£ - British Pound"),
                    ("INR", "₹ - Indian Rupee"),
                    ("CAD", "C$ - Canadian Dollar"),
                    ("AUD", "A$ - Australian Dollar"),
                    ("AED", "AED - UAE Dirham"),
                    ("SAR", "SAR - Saudi Riyal"),
                    ("JPY", "¥ - Japanese Yen"),
                    ("SGD", "S$ - Singapore Dollar"),
                ],
                default="USD",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="currency_symbol",
            field=models.CharField(default="$", max_length=10),
        ),
    ]
