# Generated by Django 5.1.15 on 2026-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="product",
            name="price_usd",
            field=models.DecimalField(
                decimal_places=2, default=5.0, help_text="Price in USD", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, help_text="Price in INR", max_digits=10
            ),
        ),
    ]
