# Generated by Django 5.1.15 on 2026-08-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_order_amount_paid_order_currency_product_price_usd_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="billing_cycle",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(default="IN", max_length=10),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="product",
            name="gst_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=18.0,
                help_text="India GST Tax Rate (%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_inr_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=199.0,
                help_text="India Monthly Price (₹)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_inr_yearly",
            field=models.DecimalField(
                decimal_places=2,
                default=1990.0,
                help_text="India Yearly Price (₹)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_usd_monthly",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="International Monthly Price ($)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_usd_yearly",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="International Yearly Price ($)",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="vat_tax_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="International Tax/VAT Rate (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="billing_type",
            field=models.CharField(
                choices=[
                    ("one_time", "One-time"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=199.0,
                help_text="Base Price (INR)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_usd",
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text="Base Price (USD)",
                max_digits=10,
            ),
        ),
    ]
