# Generated by Django 5.1.15 on 2026-08-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_order_billing_cycle_order_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                (
                    "place",
                    models.CharField(
                        help_text="Location / City / Country", max_length=200
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Specific requirements / business notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="price_inr_yearly",
            field=models.DecimalField(
                decimal_places=2,
                default=1982.0,
                help_text="India Yearly Price (₹199*12 with 17% discount)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_usd_yearly",
            field=models.DecimalField(
                decimal_places=2,
                default=49.8,
                help_text="International Yearly Price ($5*12 with 17% discount)",
                max_digits=10,
            ),
        ),
    ]
